#
# Your Crowdin credentials
#
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  "source" : "Morphic/en.lproj/Localizable.strings",
  "translation" : "Morphic/%two_letters_code%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/en.lproj/Localizable.strings",
  "translation" : "Morphic/Morphic/%two_letters_code%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/About Box/en.lproj/Localizable.strings",
  "translation" : "Morphic/Morphic/About Box/%two_letters_code%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/AutoUpdate/en.lproj/Localizable.strings",
  "translation" : "Morphic/Morphic/AutoUpdate/%two_letters_code%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/CopySettingsWindow/en.lproj/Localizable.strings",
  "translation" : "Morphic/Morphic/CopySettingsWindow/%two_letters_code%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/Permissions Guidance/en.lproj/Localizable.strings",
  "translation" : "Morphic/Morphic/Permissions Guidance/%two_letters_code%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/MorphicConfigurator/Capture/en.lproj/Localizable.strings",
  "translation" : "Morphic/MorphicConfigurator/Capture/%two_letters_code%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/MorphicConfigurator/Login/en.lproj/Localizable.strings",
  "translation" : "Morphic/MorphicConfigurator/Login/%two_letters_code%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 }
]