#
# Your Crowdin credentials
#
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  "source" : "Morphic/en.lproj/Localizable.strings",
  "translation" : "Morphic/%osx_locale%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/en.lproj/Main.strings",
  "translation" : "Morphic/Morphic/%osx_locale%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/About Box/en.lproj/*.strings",
  "translation" : "Morphic/Morphic/About Box/%osx_locale%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/AutoUpdate/en.lproj/*.strings",
  "translation" : "Morphic/Morphic/AutoUpdate/%osx_locale%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/CopySettingsWindow/en.lproj/*.strings",
  "translation" : "Morphic/Morphic/CopySettingsWindow/%osx_locale%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/Morphic/Permissions Guidance/en.lproj/*.strings",
  "translation" : "Morphic/Morphic/Permissions Guidance/%osx_locale%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/MorphicConfigurator/Capture/en.lproj/*.strings",
  "translation" : "Morphic/MorphicConfigurator/Capture/%osx_locale%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  "source" : "Morphic/MorphicConfigurator/Login/en.lproj/*.strings",
  "translation" : "Morphic/MorphicConfigurator/Login/%osx_locale%.lproj/%original_file_name%",
  "update_option" : "update_as_unapproved",
 }
]