name: Upload to Crowdin

on:
  push:
    branches: [ master ]

permissions: read-all

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.3.3
      with:
        crowdin_branch_name: morphic-macos

        upload_sources: true
        
        auto_approve_imported: true
        import_eq_suggestions: false
        
        upload_translations: true
        download_translations: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
